# -*- coding: utf-8 -*-
"""TP4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1824XKaHSN7BUyf6tTfQwgdTGW2HY_hJZ
"""

#EX1:
class square:
  def __init__(self,lenth):
    self.lenth = lenth
  def area(self):
    print("area : ",self.lenth**2)
  def perimetre(self):
    print("perimetre: ",self.lenth*4)
s=square(4)
s.area()
s.perimetre()
#EX2:
class rectangle(square):
  def __init__(self,lenth,width):
        super().__init__(lenth)
        self.width=width

#EX3:
class SampleClass:
    def __init__(self, a):
      self.__a = a
x=SampleClass(3)
print(x._SampleClass__a)
x._SampleClass__a = 23
print(x._SampleClass__a)